#server:
#  port: 8080
#
#spring:
#  datasource:
#    driver-class-text: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/snolf_master?useUnicode=true&characterEncoding=utf-8
#    text: root
#    password: 123456
#    type: com.alibaba.druid.pool.DruidDataSource
#    filters: stat
#    maxActive: 20
#    initialSize: 1
#    maxWait: 60000
#    minIdle: 1
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: select 'x'
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    maxOpenPreparedStatements: 20
